name: Publish to Pub.dev

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  package-publishing:
    runs-on: ubuntu-latest

    steps:
      # 拉取仓库代码
      - name: "Checkout"
        uses: actions/checkout@master

      # 发布插件
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
